create table if not exists public.customer_journey_events (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 8 and 100),
  event_type text not null check (event_type in (
    'page_view', 'book_photo_view', 'summary_download', 'whatsapp_opened',
    'order_started', 'delivery_selected', 'shipping_quote_requested',
    'shipping_quote_received', 'checkout_created', 'payment_page_view',
    'payment_method_selected', 'payment_submitted', 'payment_approved',
    'payment_failed'
  )),
  source text not null default 'website' check (source in ('website','whatsapp','payment','admin')),
  page_path text,
  order_id uuid references public.orders(id) on delete set null,
  conversation_id uuid references public.whatsapp_conversations(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists customer_journey_events_created_idx
  on public.customer_journey_events (created_at desc);
create index if not exists customer_journey_events_session_idx
  on public.customer_journey_events (session_id, created_at);
create index if not exists customer_journey_events_type_created_idx
  on public.customer_journey_events (event_type, created_at desc);
create index if not exists customer_journey_events_order_idx
  on public.customer_journey_events (order_id) where order_id is not null;
create index if not exists customer_journey_events_conversation_idx
  on public.customer_journey_events (conversation_id) where conversation_id is not null;

alter table public.customer_journey_events enable row level security;
grant select on public.customer_journey_events to authenticated;

create policy "Admins view customer journey events"
on public.customer_journey_events for select to authenticated
using ((select private.is_admin()));

comment on table public.customer_journey_events is
  'First-party, privacy-minimal funnel events for the Pale Panyol Fasil storefront.';
